version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "CodingButter"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      development:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
      production:
        patterns:
          - "react*"
          - "tailwindcss*"
          - "vite*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "CodingButter"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"