# Repository settings
# https://github.com/probot/settings

repository:
  name: raffle-spinner
  description: 🎡 Professional Chrome Extension for fair and transparent raffle winner selection
  homepage: https://github.com/CodingButter/raffle-spinner
  topics:
    - chrome-extension
    - raffle
    - spinner
    - react
    - typescript
    - tailwindcss
    - vite
    - monorepo
    - pnpm
    - csv-parser
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: security
    color: ee0701
    description: Security related issue or PR
  - name: performance
    color: f9d0c4
    description: Performance improvements
  - name: refactor
    color: fbca04
    description: Code refactoring
  - name: testing
    color: 0e8a16
    description: Testing related changes
  - name: ci/cd
    color: black
    description: CI/CD pipeline changes
  - name: needs-triage
    color: ffffff
    description: Needs to be triaged
  - name: priority-critical
    color: ee0701
    description: Critical priority
  - name: priority-high
    color: d93f0b
    description: High priority
  - name: priority-medium
    color: fbca04
    description: Medium priority
  - name: priority-low
    color: 0e8a16
    description: Low priority

# Milestones
milestones:
  - title: v1.0.0 - MVP Release
    description: Initial release with core functionality
    state: open
  - title: v1.1.0 - Enhanced UI
    description: UI improvements and polish
    state: open
  - title: v2.0.0 - Advanced Features
    description: Prize tiers, themes, and bulk selection
    state: open

# Branch protection
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Code Quality"
          - "Security Scan"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      restrictions:
        users: []
        teams: []
        apps: []