services:
  neo4j:
    image: neo4j:5.26.0-community
    container_name: drawday-memento-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./neo4j-import:/import
      - ./neo4j-plugins:/plugins
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/DrawDay_Memory_2025!
      
      # Database configuration
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
      
      # Enable APOC procedures
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*"
      
      # Connectors
      NEO4J_dbms_connector_bolt_enabled: "true"
      NEO4J_dbms_connector_http_enabled: "true"
      
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "DrawDay_Memory_2025!", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - memento-network

  # Optional: Neo4j backup service
  neo4j-backup:
    image: neo4j:5.26.0-community
    container_name: drawday-memento-backup
    volumes:
      - ./neo4j-backup:/backup
      - ./neo4j-data:/data:ro
    environment:
      NEO4J_AUTH: neo4j/DrawDay_Memory_2025!
    command: ["echo", "Backup container ready"]
    profiles:
      - backup
    networks:
      - memento-network

networks:
  memento-network:
    driver: bridge
    name: drawday-memento-network

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-import:
    driver: local
  neo4j-plugins:
    driver: local
  neo4j-backup:
    driver: local