name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run linter
        run: pnpm lint
      
      - name: Check formatting
        run: pnpm format:check
      
      - name: Type checking
        run: pnpm typecheck
      
      - name: Build packages
        run: pnpm build
      
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20.x'
        with:
          name: chrome-extension
          path: apps/extension/raffle-spinner-extension.zip
          retention-days: 7

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run security audit
        run: pnpm audit --audit-level=moderate
      
      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  test-extension:
    name: Test Chrome Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build extension
        run: pnpm build
      
      - name: Validate manifest
        run: |
          echo "Validating Chrome extension manifest..."
          node -e "const m = require('./apps/extension/public/manifest.json'); console.log('Manifest version:', m.manifest_version); if(m.manifest_version !== 3) throw new Error('Invalid manifest version')"
      
      - name: Check extension size
        run: |
          SIZE=$(stat -c%s apps/extension/raffle-spinner-extension.zip)
          echo "Extension size: $SIZE bytes"
          if [ $SIZE -gt 10485760 ]; then
            echo "Warning: Extension size exceeds 10MB"
            exit 1
          fi